
title: Don Lipari Projects
email: don.lipari@kvmr.org
description: >-
  Welcome to the projects of Don Lipari.
  The latest and only project is the KVRM Radio Player iPhone app.

url: "https://lipari.github.io"
github_username: lipari

# Build settings
theme: minima

